#!/bin/bash
#PBS -q workq
#PBS -l nodes=1:ppn=20
#PBS -l walltime=06:00:00
#PBS -N mini_map
#PBS -o minimap.out
#PBS -j oe
#PBS -A loni_selu_gt
#PBS -m abe
#PBS -M Rachael.johnson-2@selu.edu


datapath=/work/raechill/johnson_final  
cd $datapath

/work/raechill/minimap2-2.10_x64-linux/minimap2 -ax sr -t 20 data/Hybrid_assembly.fasta data/big_fastq > aln.sam
