#!/bin/bash
#PBS -q bigmem
#PBS -l nodes=1:ppn=24
#PBS -l walltime=24:00:00
#PBS -N pilon_improvment
#PBS -o pilon.out
#PBS -j oe
#PBS -A loni_selu_gt
#PBS -m abe
#PBS -M Rachael.johnson-2@selu.edu



datapath=/work/raechill/johnson_final/ 
cd $datapath

java -Xmx120G -jar /work/raechill/pilon-1.22.jar --threads 20 --genome data/Hybrid_assembly.fasta --outdir data/  --changes --tracks --diploid --frags sorted.bam > data/illumina-pilon.log

#java -jar /work/raechill/pilon-1.22.jar --threads 20 --mingap 20 --genome genone.bam data/Illumina_assembly.fasta --outdir data/ --changes --tracks --diploid --frags sorted.bam > illumina-$-pilon.log
