#!/bin/bash
#PBS -q workq
#PBS -l nodes=1:ppn=20
#PBS -l walltime=24:00:00
#PBS -N convert_sam_bam
#PBS -o sam.out
#PBS -j oe
#PBS -A loni_selu_gt
#PBS -m abe
#PBS -M Rachael.johnson-2@selu.edu


#### module load gcc
module load samtools
##module unload mvapich2/2.0/INTEL-14.0.2
##module load openmpi/1.8.1/INTEL-14.0.2
datapath=/work/raechill/johnson_final
cd $datapath

samtools view -S -@ 20 -b aln.sam > aln-pe.bam 
/work/raechill/sambamba_v0.6.6 sort -o sorted.bam -p -t 20 aln-pe.bam
samtools index -@ 20 sorted.bam
